### ISSUE TITLE
UNet++ model

### ISSUE THREAD

**Issue by AlessandroSaviolo** [AllentDan/SegmentationCpp#1]
Hi! Great repo!

I was exactly looking for a C++ interface to Qubvel pytorch models. Is there any possibility that you will provide the interface for the Unet++ model with SE-ResNet-50 encoder?

Thank you!

**Comment by AllentDan** [comment]
Will update later.

**Comment by AllentDan** [comment]
Hi, @AlessandroSaviolo. Thanks for your star and issue, but I have to regretfully tell your that it is much more harder than I thought to implement SeNet while keeping ResNet.  Enven though I tried template or avoid TORCH_MODULE as described in the link [here](https://discuss.pytorch.org/t/how-should-i-use-template-to-write-a-class-while-using-torch-module/113602). Besides, UNet++ could be trival but time consuming..... So, I will try again for UNet++ in one day. Wish me good.

However, If you just want to make predictions through trained UNet++ and SeNet in c++, you should better use trochscipt and torch::jit to forward a jit module like [here](https://allentdan.github.io/2021/03/05/windows-libtorch-configuration/). Or, you should try to save a ONNX file and transfer it to TensorRt like [here](https://github.com/wang-xinyu/tensorrtx), which should be faster than torchscipt.

Regard.

**Comment by AlessandroSaviolo** [comment]
Hi! Thank you very much for your effort! I actually only have to make predictions because I've already generated the trained model through qubvel pytorch implementation. I'll go through the links you have given me :)
Thank you again!
