### ISSUE TITLE
对象定位的问题？

### ISSUE THREAD

**Issue by EkilGitHub** [AllentDan/SegmentationCpp#11]
您好，我要问一下，提供的例子里面支持定位吗？比如给的image预测里面，图中有两个人，我能否把她们识别并且分别标注出来呢？
![image](https://user-images.githubusercontent.com/29229492/119816003-c3cf5100-bf1e-11eb-8e77-a324bd10c28e.png)
图中框出两人的大致轮廓。

**Comment by AllentDan** [comment]
不支持，那是实例分割。
