### ISSUE TITLE
build issue for linux

### ISSUE THREAD

**Issue by surajkhochare** [AllentDan/SegmentationCpp#12]
Hi,

Firstly, thank you for sharing this project. It would be very helpful to work with Pytorch in C++ using this library.

I tried to build the project using the commands mentioned as follows:
cd build
cmake ..
make
./LibtorchSegmentation

The "cmake .." command is executed successfully. However, the "make" command shows an error message "make: *** No targets specified and no makefile found.  Stop."
There is no makefile in the LibtorchSegmentation project directory. And therefore, there is no LibtorchSegmentation file generated in the build directory.

Please would you let me know how I can work around this?

Thanks!

**Comment by AllentDan** [comment]
Hi, @surajkhochare. Sorry for the late reply. If cmake works fine, makefiles should be generated as expected.
Not sure if you follow the correct installation commands. Do not forget to use your own libtorch path for CMAKE_PREFIX_PATH in CMakeLists.txt.
