### ISSUE TITLE
请问可以增加solov2的教程吗，球球了

### ISSUE THREAD

**Issue by woniu101** [AllentDan/SegmentationCpp#13]
非常感谢大佬开源这个项目，这对于想在C++上利用libtorch部署的人的帮助真的很大。
最近在研究solov2，但网上很多资料都是基于python的，而关于在C++上部署的非常少，不知道大佬可不可以出个相关的教程指导一下？可能这要求有点过分啦哈哈哈，但还是希望大佬能考虑一下

**Comment by AllentDan** [comment]
Hi, @gogostudy-daydayup. 这个可以参考[LibtorchTutorials](https://github.com/AllentDan/LibtorchTutorials)，找个自己心仪的repo复现到C++上，应该不是特别难。

但是里面涉及到NMS，Libtorch的API复现NMS的话，可能速度上不够好。对于双阶段的网络，NMS的框很多的话，速度比numpy实现要快，但是不会比torchvision调用cuda快，还是要直接用cuda实现的速度会好很多。不确定对solov2影响怎么样

有时间的话我会考虑做下实例分割网络的

**Comment by woniu101** [comment]
好的，非常感谢大佬的宝贵意见！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AllentDan/LibtorchSegmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月5日(星期一) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AllentDan/LibtorchSegmentation] 请问可以增加solov2的教程吗，球球了 (#13)





 
Hi, @gogostudy-daydayup. 这个可以参考LibtorchTutorials，找个自己心仪的repo复现到C++上，应该不是特别难。
 
但是里面涉及到NMS，Libtorch的API复现NMS的话，可能速度上不够好。对于双阶段的网络，NMS的框很多的话，速度比numpy实现要快，但是不会比torchvision调用cuda快，还是要直接用cuda实现的速度会好很多。
 
有时间的话我会考虑做下实例分割网络的
