### ISSUE TITLE
Adding DANNet to the supported Archs

### ISSUE THREAD

**Issue by cassini-fly** [AllentDan/SegmentationCpp#16]
Hi, Great work guys!

This is a great work indeed and I would like to contribute into it by adding a support for another network.  https://github.com/W-zx-Y/DANNet. Could you let me know the process and where is better to start? I'm sure you have done this before so I could use your experience instead of going completely on my own.

Thanks!

**Comment by AllentDan** [comment]
Hi, @cassini-fly. Sorry for the late reply. It would be really great if you can contribute DANNet. Please refer to [LibtorchTutorials](https://github.com/AllentDan/LibtorchTutorials) or directly contact me if there is something stuck you.
