### ISSUE TITLE
关于读入预训练模型的一些问题

### ISSUE THREAD

**Issue by CGump** [AllentDan/SegmentationCpp#17]
您好！学习了您的基于libtorch写的语义分割算法，我感觉收益匪浅。
在源码上还有一些问题希望能得到解答。在预测的时候看到initialize读入了resnet34.pt模型，然后在LoadWeight时又读取了segmentor.pt模型，这两个模型是一样的吗？在读入segmentor.pt时model这个类参数是不是会被覆盖，如果会被覆盖的话之前读入的resnet34这个模型好像没有必要？还有一个问题就是，训练的时候也要读入骨干网络的预训练模型，训练后保存的模型是不是已经包括了骨干网络，或者是只有一个分割头，骨干网络沿用预训练的网络参数？

还望您百忙之中能够解答，非常感谢！

**Comment by AllentDan** [comment]
@CGump Hi, 确实会被覆盖，也确实没有必要。只是读取一次权重也不占用太多资源，当时没作单独处理。训练后保存的是整个网络，包括骨干，分割头，其中骨干网络的参数是更新过的。

不客气

**Comment by CGump** [comment]
明白了~
