### ISSUE TITLE
a bug about saving the best checkpoint.

### ISSUE THREAD

**Issue by bigbigxing823** [AllentDan/SegmentationCpp#18]
https://github.com/AllentDan/LibtorchSegmentation/blob/f872f93507c4e11ab02b1b7420d5030741775744/src/Segmentor.h#L116
it seems that the min loss should be declared before training for loop.

**Comment by AllentDan** [comment]
Yeah, you are right. Could you please pull a request to help me fix this?

**Comment by bigbigxing823** [comment]
ok, done.

**Comment by AllentDan** [comment]
THX
