### ISSUE TITLE
How to convert pt-model to ONNX-model

### ISSUE THREAD

**Issue by Jessicahjj** [AllentDan/SegmentationCpp#22]
How to convert pt-model to ONNX-model? I need to load and run an ONNX-model using opencv. 
Thanks!

**Comment by AllentDan** [comment]
Define a onnx model with the exact same structure as libtorch model and copy the weight like convolution to the onnx model.

**Comment by KongCang** [comment]
Is it possible to convert a torch::nn::Module to a torch::jit::Module?

**Comment by AllentDan** [comment]
Yes. That's what I answered before.

**Comment by KongCang** [comment]
Thanks for your reply. If there is a simpler way, I will share it here.

**Comment by antithing** [comment]
Hi @KongCang did you manage to convert to onnx? Would you mind sharing your workflow? Thank you
