### ISSUE TITLE
Libtorch现阶段支持复数运算，博主什么时候能写下复数相关的运算的博客吗，等待更新。

### ISSUE THREAD

**Issue by majestichou** [AllentDan/SegmentationCpp#24]
看了您写的Libtorch的博客，受益匪浅，慕名而来，star了一下您的项目。
Libtorch现阶段支持复数运算，博主什么时候能写下复数相关的运算的博客吗，等待更新。
博主有没有相关资料的推荐，官网只给了接口，啥也没讲……

**Comment by AllentDan** [comment]
谢谢，最近都没时间做。后面空下来了可以试试。额，看源码？

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟
