### ISSUE TITLE
关于模型结构

### ISSUE THREAD

**Issue by ximitiejiang** [AllentDan/SegmentationCpp#25]
你好，看了下unet结构的实施，几个问题请教下：
- 分割头上最后为什么还接了一层upsample，按道理conv出来的特征就是(b,n_class,h,w)已经恢复到原图大小了，那这层上采样貌似不是必要的。
- dice_loss的实现：发现dice_coef的公式用了dice_coef=inter/(pred_area + label_area - inter)，但这不是iou的公式吗？dice_coef不是应该等于2*inter/(pred_area + label_area)吗？

**Comment by AllentDan** [comment]
head是公用的，不只是Unet要用。另外如果upsample输入输出分辨率相同，计算与否不影响。

dice 计算部分仔细看看，inter部分计算的是概率图乘以mask再求和。

**Comment by ximitiejiang** [comment]
另外一个问题：
- labelme的标注数据转mask时，为什么不直接绘制成单通道mask(比如填充的时候就不用name2color填充，而用name2index填充)，而是要先绘制彩色mask然后再转单通道mask？

**Comment by AllentDan** [comment]
> 另外一个问题：
> 
> * labelme的标注数据转mask时，为什么不直接绘制成单通道mask(比如填充的时候就不用name2color填充，而用name2index填充)，而是要先绘制彩色mask然后再转单通道mask？

单通道的Resize后可能出现物体边缘变成其他类，彩色的可能小很多。
