### ISSUE TITLE
How to train on custom dataset without json file?

### ISSUE THREAD

**Issue by panovr** [AllentDan/SegmentationCpp#26]
Hi, my dataset has images and corresponding masks, but it has no json files. The dataset folders just like below:
```
Dataset
├── train
│   ├── 0.png
│   ├── 0_mask.png
│   └......
├── val
│   ├── 3.png
│   ├── 3_mask.png
│   └......
```
May I ask how to train on this dataset without json file?
Thanks!

**Comment by AllentDan** [comment]
Please modify `get` func [here](https://github.com/AllentDan/LibtorchSegmentation/blob/3251e0218eb5bb9012901ce401a5b8a921f5cc31/src/SegDataset.cpp#L117) for your preference.

**Comment by antithing** [comment]
@panovr did you successfully do this? Would you be able to share your code? I am looking to train with frames and alpha matte greyscale images.
