### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by CoderDoubleTen** [AllentDan/SegmentationCpp#29]
(py37) ql@ql:~/projects/LibtorchSegmentation-main/test/build$ make
Scanning dependencies of target resnet34
[ 25%] Building CXX object CMakeFiles/resnet34.dir/resnet34.cpp.o
make[2]: *** 没有规则可制作目标“/usr/local/cuda-11.3/lib64/libcudart.so/usr/local/cuda-11.3/lib64/libcublas.so”，由“resnet34” 需求。 停止。
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/resnet34.dir/all' failed
make[1]: *** [CMakeFiles/resnet34.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AllentDan** [comment]
Sorry for the late reply. The bug was fixed. Please pull the latest codes and rebuild the tests.

**Comment by CoderDoubleTen** [comment]
Thanks! all configs success,but running problem;
(py37) ql@ql:~/projects/LibtorchSegmentation-main/test/build$ ./resnet34 
已放弃 (核心已转储)

**Comment by AllentDan** [comment]
well, you need to place model weights into program. `resenet34.pt`

**Comment by CoderDoubleTen** [comment]
I had place model weights into program.  resnet34.pt and segmentor.pt in weights, and my GPU is free

**Comment by CoderDoubleTen** [comment]
and batch_size setting 1,the same problem

**Comment by AllentDan** [comment]
Can not reproduce the error. Here is my result.
![image](https://github.com/AllentDan/LibtorchSegmentation/assets/41138331/cf370383-9902-4f01-8654-0a190bbdb806)

**Comment by AllentDan** [comment]
You may debug the program step by step.

**Comment by CoderDoubleTen** [comment]
thanks!
