### ISSUE TITLE
Instance Segmentation

### ISSUE THREAD

**Issue by Stellarto** [AllentDan/SegmentationCpp#3]
It was very helpful to implement segmentation using libTorch with C++. Thank you.
I'm trying to implement Mask R-CNN for Instance Segmentation, but I'm not fully familiar with LibTorch yet, so I'm having a hard time.
I'd like to include it in your code, so could you give me some hints?

**Comment by AllentDan** [comment]
HI，Stellarto. It will be really great if you can implement Mask R-CNN. 

Well, I assume you are familiar with pytorch Mask R-CNN. If you don't, I recommond you with this [repository](https://github.com/Okery/PyTorch-Simple-MaskRCNN). The following steps could be easy, just rewrite the code in libtorch. A libtorch tutorial repository is [here](https://github.com/AllentDan/LibtorchTutorials).

Actually, I plan to release a cpp detection repository and already finished YOLO4. YOLO5 and Faster R-CNN are the next. If you are interested, just send me your contact way to email AllentDan@gmail.com.

**Comment by Stellarto** [comment]
I think your comment will be very helpful.
Thank you very much. Let's try it with LibTorch.
Your next plan is great, too.
Thank you for your suggestion and I will contact you again as soon as I get the results.
