### ISSUE TITLE
Using DeepLabV3+?

### ISSUE THREAD

**Issue by antithing** [AllentDan/SegmentationCpp#8]
Hi, and thank you very much for making this code available. Very helpful!

I have the examples running great, but now I would like to train and use DeepLabV3+ model.

How do I generate weights and train using this model?

Thanks!

**Comment by AllentDan** [comment]
Hi. The class name is "DeepLabV3Plus", replace the class name you use now with it.

**Comment by antithing** [comment]
Hi, thank you for getting back to me. i am trying this:

```
int main(int argc, char *argv[])
{
  
    Segmentor<PAN> segmentor;
    segmentor.Initialize(0,512,512,{"background","person"},
                         "DeepLabV3Plus","E:\\Sandbox\\deep\\SegmentationCpp-main\\resnet34.pt");

    segmentor.Train(0.0003,300,4,"E:\\Sandbox\\deep\\SegmentationCpp-main\\voc_person_seg",".jpg","segmentor2.pt");

    return 0;
}
```

And it crashes without error. Where am I going wrong? Thanks again!

**Comment by AllentDan** [comment]
Replace PAN with DeepLabV3Plus. Kepp "resnet34"

**Comment by antithing** [comment]
Amazing. Thanks again!
