### ISSUE TITLE
How to enable GPU inference and how t train for multiple objects

### ISSUE THREAD

**Issue by mprabhakarece** [AllentDan/SegmentationCpp#9]
Hi,

Thank you so much for your support with my last issue.
Now I can able to run run the given code in Linux platform also.

Please let me know how to do inference with GPU.
When try to do inference using video input it is very slow. Hope GPU usage will improve the efficiency.

It is possible to train multiple objects like people, animals etc.. in a model.

Thanks and regards,
Prabhakar M

**Comment by AllentDan** [comment]
The member function Initialize accept gpu id arg... I tested 512*512 input in rtx2070s, reached 30ms for predicting. You can use better gpu cards and smaller inputs and smaller architecture....

Supports muticlass

**Comment by mprabhakarece** [comment]
@AllentDan Hi. Hope you are doing good.
If my understanding is correct gpu id should be mentioned as 0 for GPU and -1 for CPU usage.
If wrong please correct me.

**Comment by AllentDan** [comment]
Hi and Yes. You are right. Anything wrong?

**Comment by mprabhakarece** [comment]
I am using Jetson Xavier board with 512-core Volta GPU with Tensor Cores. but getting up to 5 FPS only.

**Comment by AllentDan** [comment]
What is the input and output resolution and what kind of architectures do you use? Compared with CPU, how much did the GPU speed you up?

**Comment by AllentDan** [comment]
I just checked some information about your GPU card. It seemed to be a small edge card. Maybe the libtorch inference speed can only be such high. I suggest you try TensorRt to do deployment.

BTW, I am trying to use trtorch into this project. Once succeed, the speed is supposed to be compatible with tensorrt inferencing.

**Comment by mprabhakarece** [comment]
Hi AllentDan,

I am new to deep learning. It will be helpful if I can get any hint to try this with TensorRt.

**Comment by AllentDan** [comment]
@mprabhakarece This repo may not support tensorrt in a short time. I am not quite familiar with tensorrt either.

But you can go to [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) or [tensorrtx](https://github.com/wang-xinyu/tensorrtx) for a chance.

**Comment by mprabhakarece** [comment]
@AllentDan 
Hope you are doing well. Still I working for codes with improved FPS for semantic segmentation. Is it possible to convert our segmentor.pt to onnx and then to TensorRT engine file.

**Comment by AllentDan** [comment]
The chance is slim.
